### ISSUE TITLE
Usage question about resources

### ISSUE THREAD

**Issue by abcd-ca** [JonathanWoollett-Light/redis-lock#1]
What are the resources one needs to specify here?

`let resources = vec![String::from("account1"), String::from("account2")];`

Looking at the `rslock` crate which is referenced, is it the same as the vector there? 

```rust
let rl = LockManager::new(vec![
  "redis://127.0.0.1:6380/",
  "redis://127.0.0.1:6381/",
  "redis://127.0.0.1:6382/",
]);
```

So, if I have just one Redis host, then it would be,

`let resources = vec![String::from("redis://127.0.0.1:6380/")];` ?

**Comment by abcd-ca** [comment]
Also, do I need to call release? My function is an async Axum REST API endpoint handler and I want to lock the redis calls in it. The brief example is a bit cryptic for me to understand

**Comment by JonathanWoollett-Light** [comment]
> What are the resources one needs to specify here?
> 
> let resources = vec![String::from("account1"), String::from("account2")];
> 
> Looking at the rslock crate which is referenced, is it the same as the vector there?
> 
> let rl = LockManager::new(vec![
>   "redis://127.0.0.1:6380/",
>   "redis://127.0.0.1:6381/",
>   "redis://127.0.0.1:6382/",
> ]);
> So, if I have just one Redis host, then it would be,
> 
> let resources = vec![String::from("redis://127.0.0.1:6380/")]; ?

No the `resources` are arbitrary keys; the keys you want to acquire a lock on.

I think expanding upon the given example might help, the full version is:
```rust
use redis::AsyncCommands;
#[allow(dependency_on_unit_never_type_fallback)]
fn main() -> Result<(), Box<dyn std::error::Error>> {
  tokio::runtime::Runtime::new()?.block_on(async {
      let client = todo!();
      // Setup.
      redis_lock::setup(&client).await?;
      // Get lock.
      let mut lock = redis_lock::MultiResourceLock::new(client.clone())?;
      let resources = vec![String::from("account1"), String::from("account2")];
      // Execute a function with the lock.
      lock.map_default(&resources, async move { /* .. */ }).await?;
      Ok(())
    })
}
```

E.g.
```rust
let client = todo!();
```
is where you might put
```rust
let client = redis::Client::open("redis://127.0.0.1/").unwrap();
```

> Also, do I need to call release? My function is an async Axum REST API endpoint handler and I want to lock the redis calls in it. The brief example is a bit cryptic for me to understand

In an async context I would recommend using [`map`](https://docs.rs/redis-lock/latest/redis_lock/struct.MultiResourceLock.html#method.map) or [`map_default`](https://docs.rs/redis-lock/latest/redis_lock/struct.MultiResourceLock.html#method.map_default). Looking again at the examle

```rust
// Setup.
redis_lock::setup(&client).await?;
// Get lock.
let mut lock = redis_lock::MultiResourceLock::new(client.clone())?;
let resources = vec![String::from("account1"), String::from("account2")];
// Execute a function with the lock.
lock.map_default(&resources, async move { /* YOUR CODE GOES HERE */ }).await?;
```
The lock would be acquired when your code starts and released when your code exits.

**Comment by abcd-ca** [comment]
Thank you!

That's helpful to have this additional information in the docs and I appreciate the reply.

In the meantime, my workaround was to store my redis data using a version number as part of the key then whenever something needed to be updated in the redis store, also increment a version counter key in redis. Then, any data I needed to pull out of redis would reference the latest counter value and if it was stale, it would just re-fetch and update the redis cache. This avoided the race conditions that had me reaching for this kind of plugin.
